name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Configure Git
      run: |
        git config --global user.email "altinsoy_ali@hotmail.com"
        git config --global user.name "Alim"

    - name: Install dependencies
      run: |
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk

    - name: Build APK
      run: |
        cd a
        buildozer android debug
